name: blinkapp
description: Unofficial Blink for made in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # SERVICES START
  http: ^0.13.4
  # SERVICES END

  # RIVERPOD START
  #flutter_riverpod: ^2.0.0-dev.9
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1
  # RIVERPOD END

  # ROUTING START
  go_router: ^4.1.0
  # ROUTING END

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
